### PR TITLE
adding line break to output, removing not used output var

### PR DESCRIPTION
**Pull request by casonadams**
Not sure if you mind using `println!` to output to the screen.  If you like it pull it in, if not blast it!

### CODE REVIEW

**Comment by rthomas** [comment]
Happy to use `println!`, but this change will break the functionality where a user can optionally specify an output file.

I don't like the `Box<dyn io::Write>` but haven't found a better way to do it without two completely separate paths.

**Comment by casonadams** [comment]
yeah I closed the PR because I noticed that is would break it file output.  Thinking more about this.

**Comment by rthomas** [comment]
Just to clarify - the `output` var is used and is in place to support either stdout, or writing to a file.

**Comment by rthomas** [comment]
> yeah I closed the PR because I noticed that is would break it file output. Thinking more about this.

Ok cool - happy to accept PRs cleaning it up :)

**Pull request closed without merging**
